version: 2

models:
  - name: customers  #same name as file sql
    description: "Customer Table"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
      - name: first_name
        description: "The first name of the customer"
        tests:
          - not_null
      - name: last_name
        description: "The last name of the customer"
        tests:
          - not_null